const PERMISSIONS = [
  'canRegisterWorkers', 'canEditWorkers', 'canDeleteWorkers', 'canApproveVerification',
  'canSuspendWorkers', 'canManageAttendance', 'canViewPayroll', 'canEditPayroll',
  'canManageBranches', 'canCreateStaff', 'canAssignShifts', 'canMoveWorkersBranch',
  'canSackWorkers', 'canRestoreWorkers', 'canExportReports', 'canViewAllBranches',
  'canOnlyViewAssignedBranch'
];

const ALL_PERMS = Object.fromEntries(
  ['canRegisterWorkers','canEditWorkers','canDeleteWorkers','canApproveVerification',
   'canSuspendWorkers','canManageAttendance','canViewPayroll','canEditPayroll',
   'canManageBranches','canCreateStaff','canAssignShifts','canMoveWorkersBranch',
   'canSackWorkers','canRestoreWorkers','canExportReports','canViewAllBranches',
   'canOnlyViewAssignedBranch'].map(k => [k, true])
);

const ROLE_DEFAULTS = {
  company_admin: { ...ALL_PERMS, canOnlyViewAssignedBranch: false },
  branch_manager: {
    canRegisterWorkers: true,
    canEditWorkers: true,
    canDeleteWorkers: false,
    canApproveVerification: false,
    canSuspendWorkers: true,
    canManageAttendance: true,
    canViewPayroll: true,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: true,
    canMoveWorkersBranch: true,
    canSackWorkers: false,
    canRestoreWorkers: true,
    canExportReports: true,
    canViewAllBranches: false,
    canOnlyViewAssignedBranch: true,
  },
  hr_staff: {
    canRegisterWorkers: true,
    canEditWorkers: true,
    canDeleteWorkers: false,
    canApproveVerification: false,
    canSuspendWorkers: false,
    canManageAttendance: true,
    canViewPayroll: true,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: false,
    canMoveWorkersBranch: false,
    canSackWorkers: false,
    canRestoreWorkers: false,
    canExportReports: true,
    canViewAllBranches: true,
    canOnlyViewAssignedBranch: false,
  },
  attendance_officer: {
    canRegisterWorkers: false,
    canEditWorkers: false,
    canDeleteWorkers: false,
    canApproveVerification: false,
    canSuspendWorkers: false,
    canManageAttendance: true,
    canViewPayroll: false,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: false,
    canMoveWorkersBranch: false,
    canSackWorkers: false,
    canRestoreWorkers: false,
    canExportReports: false,
    canViewAllBranches: false,
    canOnlyViewAssignedBranch: true,
  },
  verification_officer: {
    canRegisterWorkers: false,
    canEditWorkers: false,
    canDeleteWorkers: false,
    canApproveVerification: true,
    canSuspendWorkers: false,
    canManageAttendance: false,
    canViewPayroll: false,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: false,
    canMoveWorkersBranch: false,
    canSackWorkers: false,
    canRestoreWorkers: false,
    canExportReports: false,
    canViewAllBranches: true,
    canOnlyViewAssignedBranch: false,
  },
  staff: {
    canRegisterWorkers: false,
    canEditWorkers: false,
    canDeleteWorkers: false,
    canApproveVerification: false,
    canSuspendWorkers: false,
    canManageAttendance: false,
    canViewPayroll: false,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: false,
    canMoveWorkersBranch: false,
    canSackWorkers: false,
    canRestoreWorkers: false,
    canExportReports: false,
    canViewAllBranches: false,
    canOnlyViewAssignedBranch: true,
  },
};

const PRESETS = {
  fullHR: {
    canRegisterWorkers: true,
    canEditWorkers: true,
    canDeleteWorkers: false,
    canApproveVerification: false,
    canSuspendWorkers: true,
    canManageAttendance: true,
    canViewPayroll: true,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: true,
    canMoveWorkersBranch: true,
    canSackWorkers: false,
    canRestoreWorkers: true,
    canExportReports: true,
    canViewAllBranches: true,
    canOnlyViewAssignedBranch: false,
  },
  attendance: {
    canRegisterWorkers: false,
    canEditWorkers: false,
    canDeleteWorkers: false,
    canApproveVerification: false,
    canSuspendWorkers: false,
    canManageAttendance: true,
    canViewPayroll: false,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: false,
    canMoveWorkersBranch: false,
    canSackWorkers: false,
    canRestoreWorkers: false,
    canExportReports: false,
    canViewAllBranches: false,
    canOnlyViewAssignedBranch: true,
  },
  verification: {
    canRegisterWorkers: false,
    canEditWorkers: false,
    canDeleteWorkers: false,
    canApproveVerification: true,
    canSuspendWorkers: false,
    canManageAttendance: false,
    canViewPayroll: false,
    canEditPayroll: false,
    canManageBranches: false,
    canCreateStaff: false,
    canAssignShifts: false,
    canMoveWorkersBranch: false,
    canSackWorkers: false,
    canRestoreWorkers: false,
    canExportReports: false,
    canViewAllBranches: true,
    canOnlyViewAssignedBranch: false,
  },
  none: Object.fromEntries(
    ['canRegisterWorkers','canEditWorkers','canDeleteWorkers','canApproveVerification',
     'canSuspendWorkers','canManageAttendance','canViewPayroll','canEditPayroll',
     'canManageBranches','canCreateStaff','canAssignShifts','canMoveWorkersBranch',
     'canSackWorkers','canRestoreWorkers','canExportReports','canViewAllBranches',
     'canOnlyViewAssignedBranch'].map(k => [k, false])
  ),
};

module.exports = { PERMISSIONS, ROLE_DEFAULTS, PRESETS };
